name: Release Docs

on:
  push:
    tags: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Set up Pages
      uses: actions/configure-pages@v1
      
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.8'
        
    - name: Generate Docs
      run: xcodebuild docbuild -scheme didcomm-swift -destination "platform=macOS" -derivedDataPath ./doccBuild OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path ./docc --hosting-base-path '/didcomm-swift'"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v1
