name: Release

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild build test -scheme "didcomm-swift" -destination "platform=macOS" -resultBundlePath TestResults
